### PR TITLE
Image Classification Notebook Example for Docs

### PR DESCRIPTION
**Pull request by simonrmonk**
<summary of the change, relevant motivation, and context>

Change type:

- [ ] Bug fix
- [ ] Feature
- [x] Documentation

Checklist:

- [ ] My code follows the style guidelines of this [project](https://docs.google.com/document/d/1jckZJe0CrWyF-IjxoO2OfBKAyKLC3Yk9Xr7UmOLBETA/edit?usp=sharing)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code and added docstrings to all exposed functions and classes
- [ ] I have made corresponding changes to the documentation
- [ ] Any relevant changes to third party licenses have been updated in the README

### CODE REVIEW

**Review by timesler — COMMENTED** [review]
@simonrmonk this is fantastic work

Can you test and see if running `pip install .` includes the docs folder (and hence the notebook files) in the package files installed in the python package directory? I'm fine having the notebooks in the repo, but we should make sure they don't get included when someone runs `pip install xt-training` as it will make the package size much bigger.

A few other notes:

When I look at the published [docs page](https://xt-training.readthedocs.io/en/image_classification_example/Image-Classification/), the cell count starts at "In [19]:" instead of 1. I think we should hide these cell counts altogether if possible. If not, lets just make sure they start at one (I assume we just need to rerun the notebook on a fresh kernel).

A few typos/notes from the doc: 
* At the bottom, you say "Now, let's train one additional epoch with the model we had previously trained using the Runner API.". However, you have reinstantiated the model just above this. Do you mean "Functional API"? And did you mean to instantiate the model again to overwrite the prior training?
* Explicitly is spelt wrong as "explicitely" about 1/3 of the way down.
* We should add a title to the document
* Mkdocs has quite nice automatic generation of sub-page table of contents in the side bar, but it only works with level 2 headers (i.e., `##`). We should add a title (`#`) and make the level 2 header use `##`

**Comment by timesler** [comment]
Update: pushed a small change that removes the cell margins.

**Comment by timesler** [comment]
~~Actually, that css change only seems to take effect when I do `mkdocs serve`, doesn't seem to be working in the hosted version on ReadTheDocs~~

EDIT: It works, just had to wait 10 minutes.

**Comment by simonrmonk** [comment]
Hi @timesler, thanks for the feedback and the help improving the look of the notebook. I've accommodated your feedback and added comments below in **bold**. Let me know if you have any more feedback.

> @simonrmonk this is fantastic work
> 
> Can you test and see if running `pip install .` includes the docs folder (and hence the notebook files) in the package files installed in the python package directory? I'm fine having the notebooks in the repo, but we should make sure they don't get included when someone runs `pip install xt-training` as it will make the package size much bigger.
* **I have confirmed that, with the way we have our setup.py file configured, we are not installing the docs directory as part of xt-training.**
> 
> A few other notes:
> 
> When I look at the published [docs page](https://xt-training.readthedocs.io/en/image_classification_example/Image-Classification/), the cell count starts at "In [19]:" instead of 1. I think we should hide these cell counts altogether if possible. If not, lets just make sure they start at one (I assume we just need to rerun the notebook on a fresh kernel).
* **Thank you for looking into this, it looks much better now.**
> 
> A few typos/notes from the doc:
> 
> At the bottom, you say "Now, let's train one additional epoch with the model we had previously trained using the Runner API.". However, you have reinstantiated the model just above this. Do you mean "Functional API"? And did you mean to instantiate the model again to overwrite the prior training?
* **Actually, the notebook was doing what I was intending; however the English was poor and I didn't properly explain why I was doing it this way. My intention was just to highlight for the user how to load the model weights back in before training for another epoch. This is a little bit out of scope though and so for now I've removed this part of the code. I've updated the notebook so it is just running another epoch using the Runner API for the same model instance trained by the Functional API.**

> 
> * Explicitly is spelt wrong as "explicitely" about 1/3 of the way down.
* **Good catch, this is fixed now. Thank you.**
> 
> * We should add a title to the document
* **Title added.**
> 
> * Mkdocs has quite nice automatic generation of sub-page table of contents in the side bar, but it only works with level 2 headers (i.e., `##`). We should add a title (`#`) and make the level 2 header use `##`
* **Got it. I've adjusted the headers.**

**Review by timesler — APPROVED** [review]
Excellent work

**Pull request merged**
